force-app/main/default/objects/Dynacat_Attribute__c/Dynacat_Attribute__c.object-meta.xml
<CustomObject>
    <label>Attribute</label>
    <nameField>
        <label>Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dynacat_Attribute__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dynacat_Attribute__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dynacat_Attribute__c/fields/Parent_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Parent_Attribute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Attribute</label>
    <referenceTo>Dynacat_Attribute__c</referenceTo>
    <relationshipLabel>Attributes</relationshipLabel>
    <relationshipName>Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dynacat_Attribute__c/fields/Selectable__c.field-meta.xml
<CustomField>
    <fullName>Selectable__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Selectable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DynacatTests.cls
// Very basic test stubs only
//
@isTest
private class DynacatTests {

    @testSetup static void setupTestData() {
        Product2 p = new Product2();
        p.Name = 'Test Product';
      //  p.External_Id__c = 'T123';
      //  p.Status__c = 'Active';
        insert(p);
        
        Dynacat_Attribute__c a = new Dynacat_Attribute__c();
        a.Name = 'Test Root Attribute';
        a.Order__c = 1;
        a.Selectable__c = true;
        a.Active__c = true;
        a.External_Id__c = 'T0';
        insert(a);
        
        Dynacat_Attribute__c a2 = new Dynacat_Attribute__c();
        a2.Name = 'Test Child Attribute';
        a2.Order__c = 1;
        a2.Selectable__c = true;
        a2.Active__c = true;
        a2.External_Id__c = 'T1';
        a2.Parent_Attribute__c = a.Id;
        insert(a2);  
        
        Dynacat_Attribute__c a3 = new Dynacat_Attribute__c();
        a3.Name = 'Test Grandchild Attribute';
        a3.Order__c = 1;
        a3.Selectable__c = true;
        a3.Active__c = true;
        a3.External_Id__c = 'T2';
        a3.Parent_Attribute__c = a2.Id;
        insert(a3); 
        
        Dynacat_Attribute__c a4 = new Dynacat_Attribute__c();
        a4.Name = 'Test Child Attribute 2';
        a4.Order__c = 2;
        a4.Selectable__c = true;
        a4.Active__c = true;
        a4.External_Id__c = 'T3';
        a4.Parent_Attribute__c = a.Id;
        insert(a4); 
        
        List<String> atts = new List<String>{a2.External_Id__c};
        DynacatAttSelectorController.saveRecordAttributes(JSON.serialize(atts), p.Id, 'Product2', 'Product2__c', 'Id');
        
    }
    
    @isTest static void testAttributes() {
        Product2 p = [SELECT Id FROM Product2 WHERE Name='Test Product'];
        Test.startTest();
        String attributes = DynacatAttSelectorController.getActiveAttributes(p.Id, 'Product2', 'Product2__c');
        Test.stopTest();
        System.debug(attributes);
    }
    @isTest static void testAttributeSave() {
        Product2 p = [SELECT Id FROM Product2 WHERE Name='Test Product'];
        Dynacat_Attribute__c a = [SELECT External_Id__c FROM Dynacat_Attribute__c WHERE Name = 'Test Grandchild Attribute'];
        List<String> atts = new List<String>{a.External_Id__c};
        Test.startTest();
        DynacatAttSelectorController.saveRecordAttributes(JSON.serialize(atts), p.Id, 'Product2', 'Product2__c', 'Id');
        Test.stopTest();
    }
    @isTest static void testCatalog2() {
        Test.startTest();
        String attributes = DynacatCatalogFiltersController.getActiveAttributes();
        Test.stopTest();
        System.debug(attributes);   
    }
    @isTest static void testCatalog() {
        Test.startTest();
//        String prods = CatalogMethods.getActiveProducts();
        Test.stopTest();
    }
   
}